#AndroidIDE: enforce UTF-8 & locale for Gradle daemon
#Mon Nov 10 02:24:10 GMT 2025
android.nonTransitiveRClass=true
systemProp.user.language=en
systemProp.user.country=US
systemProp.sun.jnu.encoding=UTF-8
systemProp.file.encoding=UTF-8
systemProp.java.net.preferIPv4Stack=true
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding\=UTF-8 -Djava.net.preferIPv4Stack\=true
android.useAndroidX=true
android.dependency.useConstraints=false
android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false
android.uniquePackageNames=false
android.r8.strictFullModeForKeepRules=false

# Redirigir la caché de Gradle de usuario a /tmp para no llenar el disco persistente
systemProp.gradle.user.home=/tmp/.gradle
gradle.user.home=/tmp/.gradle
